name: EditorConfig Check

on: [push, pull_request]

jobs:
  editorconfig-check:
    runs-on: ubuntu-latest

    env:
      EC_VERSION: "v3.0.3"
      EC_OS: "linux"
      EC_ARCH: "amd64"

    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Install EditorConfig Checker
    - name: Install EditorConfig Checker
      run: |
        curl -O -L -C - https://github.com/editorconfig-checker/editorconfig-checker/releases/download/$EC_VERSION/ec-$EC_OS-$EC_ARCH.tar.gz
        tar xzf ec-$EC_OS-$EC_ARCH.tar.gz

    # Verify Installation
    - name: Verify EditorConfig Checker
      run: |
        ./bin/ec-$EC_OS-$EC_ARCH --version

    # Run EditorConfig Checker
    - name: Run EditorConfig Checker
      run: |
        ./bin/ec-$EC_OS-$EC_ARCH

